# Dockerfile.web
FROM python:3.10-slim

WORKDIR /app

# Copy Flask app & requirements
COPY web ./web
COPY data ./data
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000
CMD ["python", "web/app.py"]
